/* eslint-disable */
let instance = null;
import React from "react";
import Color from "./styles/color";
import Elavated from "./customize/ElevatedView";
import ReadMore from "./customize/ReadMore";
import Card from "./images/cards/index";
import Home from "./svg/Home";
import _ from "lodash";

class ImgResource {
	static getInstance() {
		if (!instance) {
			instance = new ImgResource();
		}

		return instance;
	}

	constructor() {

		this.imgs = {
			// COUNTRY FLAG
			none: require("./images/flag/(none).png"),
			ad: require("./images/flag/ad.png"),
			AED: require("./images/flag/AED.png"),
			AFN: require("./images/flag/AFN.png"),
			ALL: require("./images/flag/ALL.png"),
			AMD: require("./images/flag/AMD.png"),
			ANG: require("./images/flag/ANG.png"),
			AOA: require("./images/flag/AOA.png"),
			ARS: require("./images/flag/ARS.png"),
			as: require("./images/flag/as.png"),
			at: require("./images/flag/at.png"),
			AUD: require("./images/flag/AUD.png"),
			AWG: require("./images/flag/AWG.png"),
			ax: require("./images/flag/ax.png"),
			AZN: require("./images/flag/AZN.png"),
			BAM: require("./images/flag/BAM.png"),
			BBD: require("./images/flag/BBD.png"),
			BDT: require("./images/flag/BDT.png"),
			be: require("./images/flag/be.png"),
			bf: require("./images/flag/bf.png"),
			BGN: require("./images/flag/BGN.png"),
			BHD: require("./images/flag/BHD.png"),
			BIF: require("./images/flag/BIF.png"),
			BMD: require("./images/flag/BMD.png"),
			BND: require("./images/flag/BND.png"),
			BOB: require("./images/flag/BOB.png"),
			BRL: require("./images/flag/BRL.png"),
			BSD: require("./images/flag/BSD.png"),
			BTN: require("./images/flag/BTN.png"),
			BWP: require("./images/flag/BWP.png"),
			BYN: require("./images/flag/BYN.png"),
			BYR: require("./images/flag/BYR.png"),
			BZD: require("./images/flag/BZD.png"),
			CAD: require("./images/flag/CAD.png"),
			CDF: require("./images/flag/CDF.png"),
			cf: require("./images/flag/cf.png"),
			cg: require("./images/flag/cg.png"),
			CHF: require("./images/flag/CHF.png"),
			ci: require("./images/flag/ci.png"),
			CKD: require("./images/flag/CKD.png"),
			CLP: require("./images/flag/CLP.png"),
			CNY: require("./images/flag/CNY.png"),
			COP: require("./images/flag/COP.png"),
			CRC: require("./images/flag/CRC.png"),
			CUC: require("./images/flag/CUC.png"),
			CUP: require("./images/flag/CUP.png"),
			CVE: require("./images/flag/CVE.png"),
			cx: require("./images/flag/cx.png"),
			cy: require("./images/flag/cy.png"),
			CZK: require("./images/flag/CZK.png"),
			de: require("./images/flag/de.png"),
			DJF: require("./images/flag/DJF.png"),
			DKK: require("./images/flag/DKK.png"),
			dm: require("./images/flag/dm.png"),
			DOP: require("./images/flag/DOP.png"),
			DZD: require("./images/flag/DZD.png"),
			ec: require("./images/flag/ec.png"),
			ee: require("./images/flag/ee.png"),
			EGP: require("./images/flag/EGP.png"),
			ERN: require("./images/flag/ERN.png"),
			es: require("./images/flag/es.png"),
			ETB: require("./images/flag/ETB.png"),
			EUR: require("./images/flag/EUR.png"),
			fi: require("./images/flag/fi.png"),
			FJD: require("./images/flag/FJD.png"),
			FKP: require("./images/flag/FKP.png"),
			fm: require("./images/flag/fm.png"),
			fr: require("./images/flag/fr.png"),
			ga: require("./images/flag/ga.png"),
			GBP: require("./images/flag/GBP.png"),
			gd: require("./images/flag/gd.png"),
			GEL: require("./images/flag/GEL.png"),
			gg: require("./images/flag/gg.png"),
			GHS: require("./images/flag/GHS.png"),
			GIP: require("./images/flag/GIP.png"),
			gl: require("./images/flag/gl.png"),
			GMD: require("./images/flag/GMD.png"),
			GNF: require("./images/flag/GNF.png"),
			gq: require("./images/flag/gq.png"),
			gr: require("./images/flag/gr.png"),
			gs: require("./images/flag/gs.png"),
			GTQ: require("./images/flag/GTQ.png"),
			gu: require("./images/flag/gu.png"),
			gw: require("./images/flag/gw.png"),
			GYD: require("./images/flag/GYD.png"),
			HKD: require("./images/flag/HKD.png"),
			HNL: require("./images/flag/HNL.png"),
			HRK: require("./images/flag/HRK.png"),
			HTG: require("./images/flag/HTG.png"),
			HUF: require("./images/flag/HUF.png"),
			IDR: require("./images/flag/IDR.png"),
			ie: require("./images/flag/ie.png"),
			ILS: require("./images/flag/ILS.png"),
			INR: require("./images/flag/INR.png"),
			io: require("./images/flag/io.png"),
			IQD: require("./images/flag/IQD.png"),
			IRR: require("./images/flag/IRR.png"),
			ISK: require("./images/flag/ISK.png"),
			it: require("./images/flag/it.png"),
			JMD: require("./images/flag/JMD.png"),
			JOD: require("./images/flag/JOD.png"),
			JPY: require("./images/flag/JPY.png"),
			KES: require("./images/flag/KES.png"),
			KGS: require("./images/flag/KGS.png"),
			KHR: require("./images/flag/KHR.png"),
			ki: require("./images/flag/ki.png"),
			KMF: require("./images/flag/KMF.png"),
			kn: require("./images/flag/kn.png"),
			kp: require("./images/flag/kp.png"),
			KPW: require("./images/flag/KPW.png"),
			KRW: require("./images/flag/KRW.png"),
			KWD: require("./images/flag/KWD.png"),
			KYD: require("./images/flag/KYD.png"),
			KZT: require("./images/flag/KZT.png"),
			LAK: require("./images/flag/LAK.png"),
			LBP: require("./images/flag/LBP.png"),
			LKR: require("./images/flag/LKR.png"),
			LRD: require("./images/flag/LRD.png"),
			LSL: require("./images/flag/LSL.png"),
			LYD: require("./images/flag/LYD.png"),
			MAD: require("./images/flag/MAD.png"),
			MDL: require("./images/flag/MDL.png"),
			MGA: require("./images/flag/MGA.png"),
			MKD: require("./images/flag/MKD.png"),
			MMK: require("./images/flag/MMK.png"),
			MNT: require("./images/flag/MNT.png"),
			MOP: require("./images/flag/MOP.png"),
			MRO: require("./images/flag/MRO.png"),
			MUR: require("./images/flag/MUR.png"),
			MVR: require("./images/flag/MVR.png"),
			MWK: require("./images/flag/MWK.png"),
			MXN: require("./images/flag/MXN.png"),
			MYR: require("./images/flag/MYR.png"),
			MZN: require("./images/flag/MZN.png"),
			NAD: require("./images/flag/NAD.png"),
			NGN: require("./images/flag/NGN.png"),
			NIO: require("./images/flag/NIO.png"),
			NOK: require("./images/flag/NOK.png"),
			NPR: require("./images/flag/NPR.png"),
			NZD: require("./images/flag/NZD.png"),
			OMR: require("./images/flag/OMR.png"),
			PAB: require("./images/flag/PAB.png"),
			PEN: require("./images/flag/PEN.png"),
			PGK: require("./images/flag/PGK.png"),
			PHP: require("./images/flag/php.png"),
			PKR: require("./images/flag/PKR.png"),
			PLN: require("./images/flag/PLN.png"),
			PYG: require("./images/flag/PYG.png"),
			QAR: require("./images/flag/QAR.png"),
			RON: require("./images/flag/RON.png"),
			RSD: require("./images/flag/RSD.png"),
			RUB: require("./images/flag/RUB.png"),
			RWF: require("./images/flag/RWF.png"),
			SAR: require("./images/flag/SAR.png"),
			SBD: require("./images/flag/SBD.png"),
			SCR: require("./images/flag/SCR.png"),
			SDG: require("./images/flag/SDG.png"),
			SEK: require("./images/flag/SEK.png"),
			SGD: require("./images/flag/SGD.png"),
			SHP: require("./images/flag/SHP.png"),
			si: require("./images/flag/si.png"),
			sk: require("./images/flag/sk.png"),
			SLL: require("./images/flag/SLL.png"),
			sm: require("./images/flag/sm.png"),
			SOS: require("./images/flag/SOS.png"),
			SRD: require("./images/flag/SRD.png"),
			SSP: require("./images/flag/SSP.png"),
			STD: require("./images/flag/STD.png"),
			SYP: require("./images/flag/SYP.png"),
			SZL: require("./images/flag/SZL.png"),
			THB: require("./images/flag/THB.png"),
			TJS: require("./images/flag/TJS.png"),
			TMT: require("./images/flag/TMT.png"),
			TND: require("./images/flag/TND.png"),
			TOP: require("./images/flag/TOP.png"),
			TRY: require("./images/flag/TRY.png"),
			TTD: require("./images/flag/TTD.png"),
			TWD: require("./images/flag/TWD.png"),
			TZS: require("./images/flag/TZS.png"),
			UAH: require("./images/flag/UAH.png"),
			UGX: require("./images/flag/UGX.png"),
			USD: require("./images/flag/USD.png"),
			UYU: require("./images/flag/UYU.png"),
			UZS: require("./images/flag/UZS.png"),
			va: require("./images/flag/va.png"),
			vc: require("./images/flag/vc.png"),
			VEF: require("./images/flag/VEF.png"),
			vg: require("./images/flag/vg.png"),
			vi: require("./images/flag/vi.png"),
			VND: require("./images/flag/VND.png"),
			VUV: require("./images/flag/VUV.png"),
			wf: require("./images/flag/wf.png"),
			WST: require("./images/flag/WST.png"),
			XAF: require("./images/flag/XAF.png"),
			XCD: require("./images/flag/XCD.png"),
			XOF: require("./images/flag/XOF.png"),
			XPF: require("./images/flag/XPF.png"),
			YER: require("./images/flag/YER.png"),
			yt: require("./images/flag/yt.png"),
			yu: require("./images/flag/yu.png"),
			ZAR: require("./images/flag/ZAR.png"),
			ZMW: require("./images/flag/ZMW.png"),
			zw: require("./images/flag/zw.png"),

			// QR CODE
			qr_frame: require("./images/qr/qr_frame.png"),
			qr_regcode: require("./images/qr/qr_regcode.png"),
			qr_download: require("./images/qr/qr_download.png"),
			qr_code: require("./images/qr/qr_code.png"),
			camera_active: require("./images/qr/camera_active.png"),
			camera_nonactive: require("./images/qr/camera_nonactive.png"),
			qr_scan_active: require("./images/qr/qr_scan_active.png"),
			qr_scan_nonactive: require("./images/qr/qr_scan_nonactive.png"),
			qr_dark: require("./images/qr/qr_dark.png"),
			gallery: require("./images/qr/gallery.png"),

			// WALLET SERVICES
			button_convert: require("./images/wallet/button_convert.png"),
			button_fundrequest: require("./images/wallet/button_fundrequest.png"),
			button_history: require("./images/wallet/button_history.png"),
			button_points: require("./images/wallet/button_points.png"),
			button_send_ecash: require("./images/wallet/button_send_ecash.png"),
			button_wallet: require("./images/wallet/button_wallet.png"),
			button_switch: require("./images/wallet/button_switch.png"),
			button_camera: require("./images/wallet/camera_button.png"),
			button_update: require("./images/wallet/update_button.png"),

			// LOGO's
			unified_logo: require("./images/logo/unified_logo.png"),
			official_store_logo: require("./images/logo/official_store_logo.png"),
			bentanayan_logo: require("./images/logo/bentanayan_logo.png"),
			phillands_logo: require("./images/logo/phillands_logo.png"),
			automobile_logo: require("./images/logo/automobile_logo.png"),
			ecash_logo: require("./images/logo/ecash_logo.png"),
			GLOBE: require("./images/logo/globe_logo.png"),
			SUN: require("./images/logo/sun_logo.png"),
			SMART: require("./images/logo/smart_logo.png"),
			TM: require("./images/logo/tm_logo.png"),
			TNT: require("./images/logo/tnt_logo.png"),
			ups: require("./images/logo/ups_logo.png"),
			u_legit_logo: require("./images/logo/u_legit_logo.png"),

			// SAMPLE IMAGES
			slider_1: require("./images2/slider_1.jpg"),
			slider_2: require("./images2/slider_2.jpg"),
			home_image_1: require("./images2/home_image_1.jpg"),
			home_image_2: require("./images2/home_image_2.jpg"),
			home_image_3: require("./images2/home_image_3.jpg"),
			item_A_1: require("./images2/item_A_1.png"),
			item_A_2: require("./images2/item_A_2.png"),
			item_A_3: require("./images2/item_A_3.png"),
			item_A_4: require("./images2/item_A_4.png"),
			item_A_5: require("./images2/item_A_5.png"),
			item_B_1: require("./images2/item_B_1.png"),
			item_B_2: require("./images2/item_B_2.png"),
			item_B_3: require("./images2/item_B_3.png"),
			item_B_4: require("./images2/item_B_4.png"),
			item_B_5: require("./images2/item_B_5.png"),
			item_B_6: require("./images2/item_B_6.png"),
			ads: require("./images2/ads.jpg"),
			poweredby: require("./images2/powered_by.png"),

			// BOTTOM TABBAR
			menu_home: require("./images/tabbar/menu_home.png"),
			menu_home_tint: require("./images/tabbar/menu_home_tint.png"),
			menu_inbox: require("./images/tabbar/menu_inbox.png"),
			menu_inbox_tint: require("./images/tabbar/menu_inbox_tint.png"),
			menu_notif: require("./images/tabbar/menu_notif.png"),
			menu_notif_tint: require("./images/tabbar/menu_notif_tint.png"),
			menu_profile: require("./images/tabbar/menu_profile.png"),
			menu_profile_tint: require("./images/tabbar/menu_profile_tint.png"),
			menu_wallet: require("./images/tabbar/menu_wallet.png"),
			menu_wallet_tint: require("./images/tabbar/menu_wallet_tint.png"),
			online_store_cart: require("./images/tabbar/online_store_cart.png"),
			online_store_cart_tint: require("./images/tabbar/online_store_cart_tint.png"),
			online_store_home: require("./images/tabbar/online_store_home.png"),
			online_store_home_tint: require("./images/tabbar/online_store_home_tint.png"),

			//onlinestore/icon
			onlinestoreNavTitle: require("../resources/images/onlinestoreicons/shopping-online3x.png"),
			back: require("../resources/images/onlinestoreicons/back.png"),
			back_white: require("../resources/images/onlinestoreicons/back_white.png"),
			change_arrow: require("./images/onlinestoreicons/change-arrows.png"),
			shopping_bag: require("./images/onlinestoreicons/shopping-bag.png"),
			profile_user: require("./images/onlinestoreicons/profile_user.png"),
			processing: require("./images/onlinestoreicons/processing.png"),
			to_ship: require("./images/onlinestoreicons/to-ship.png"),
			shipped: require("./images/onlinestoreicons/shipped.png"),
			delivered: require("./images/onlinestoreicons/delivered.png"),
			refund_pending: require("./images/onlinestoreicons/refund-pending.png"),
			refund_approved: require("./images/onlinestoreicons/refund-approved.png"),
			refund_declined: require("./images/onlinestoreicons/refund-declined.png"),
			despute_pending: require("./images/onlinestoreicons/despute-pending.png"),
			despute_approved: require("./images/onlinestoreicons/despute-approved.png"),
			despute_declined: require("./images/onlinestoreicons/despute-declined.png"),
			manage_product: require("./images/onlinestoreicons/manage_product.png"),
			add_product: require("./images/onlinestoreicons/add_product.png"),
			online_store_dashboard: require("./images/onlinestoreicons/dashboard.png"),
			online_store_dashboard_tint: require("./images/onlinestoreicons/dashboard_tinted.png"),
			online_store_notifications: require("./images/onlinestoreicons/notifications.png"),
			online_store_notifications_tint: require("./images/onlinestoreicons/notifications_tint.png"),
			online_store_chats: require("./images/onlinestoreicons/chats.png"),
			online_store_chats_tint: require("./images/onlinestoreicons/chats_tint.png"),
			online_store_filter: require("./images/onlinestoreicons/filter.png"),
			shipping: require("./images/onlinestoreicons/shipping.png"),
			delivery_options: require("./images/onlinestoreicons/deliveryOptions.png"),
			bookmark: require("./images/onlinestoreicons/bookmark.png"),
			delete_address: require("./images/onlinestoreicons/delete_address.png"),
			edit_address: require("./images/onlinestoreicons/edit_address.png"),
			online_store_cart_white: require("./images/onlinestoreicons/online_store_cart_white.png"),
			chat_test: require("./images/onlinestoreicons/chat_test.png"),
			order_image_test: require("./images/onlinestoreicons/order_image_test.png"),
			promotions_test: require("./images/onlinestoreicons/promotions_test.png"),
			settings_test: require("./images/onlinestoreicons/settings_test.png"),
			settings_icon: require("./images/onlinestoreicons/settings_icon.png"),
			reports_icon: require("./images/onlinestoreicons/reports_icon.png"),
			prof_icon: require("./images/onlinestoreicons/prof_icon.png"),
			transactions_icon: require("./images/onlinestoreicons/transactions_icon.png"),
			dashboard_icon: require("./images/onlinestoreicons/dashboard_icon.png"),
			notif_icon: require("./images/onlinestoreicons/notif_icon.png"),
			cart_icon: require("./images/onlinestoreicons/cart_icon.png"),
			favorites_icon: require("./images/onlinestoreicons/favorites_icon.png"),
			settings_system_update: require("./images/onlinestoreicons/settings_system_update.png"),
			settings_order_update: require("./images/onlinestoreicons/settings_order_update.png"),
			settings_comments: require("./images/onlinestoreicons/settings_comments.png"),
			settings_chat: require("./images/onlinestoreicons/settings_chat.png"),
			settings_mp_promotions: require("./images/onlinestoreicons/settings_mp_promotions.png"),
			dashboard_collection: require("./images/onlinestoreicons/dashboard_collection.png"),
			dashboard_mysales: require("./images/onlinestoreicons/dashboard_mysales.png"),
			dashboard_reports: require("./images/onlinestoreicons/dashboard_reports.png"),
			dashboard_shop: require("./images/onlinestoreicons/dashboard_shop.png"),
			mp_bdo: require("./images/onlinestoreicons/bdo.png"),
			mp_sec_bank: require("./images/onlinestoreicons/sec_bank.png"),
			store_name: require("./images/onlinestoreicons/store-name.png"),
			discount_banner: require("./images/onlinestoreicons/discount_banner.png"),
			store_cancelled: require("./images/onlinestoreicons/store-cancelled.png"),
			store_products: require("./images/onlinestoreicons/store-products.png"),
			store_delivery_duration: require("./images/onlinestoreicons/store-delivery-duration.png"),
			store_ratings: require("./images/onlinestoreicons/store-ratings.png"),
			transaction_success: require("./images/onlinestoreicons/TransactionSuccess.png"),
			logo_description: require("./images/onlinestoreicons/logo_description.png"),
			product_collections: require("./images/onlinestoreicons/product_collections.png"),
			no_products: require("./images/onlinestoreicons/no_products.png"),

			next: require("./images/next.png"),
			sms_icon: require("./images/sms_icon.png"),
			email_icon: require("./images/email_icon.png"),
			check_icon: require("./images/check_icon.png"),
			view_icon: require("./images/view_icon.png"),
			view_icon_new: require("./images/view_icon_new.png"),
			hide_icon_new: require("./images/hide_icon_new.png"),
			lock_icon: require("./images/lock_icon.png"),
			profile_icon: require("./images/profile_icon.png"),
			fb: require("./images/fb_icon.png"),
			date_icon: require("./images/date_icon.png"),
			profile_circle: require("./images/profile_circle.png"),
			mascot_happy: require("./images/mascot_happy.png"),
			mascot_sad: require("./images/mascot_sad.png"),
			mascot_surprised: require("./images/mascot_surprised.png"),
			otp_image: require("./images/otp_image.png"),
			burger_menu: require("./images/burger_menu.png"),
			background_mp: require("./images/background_mp.png"),
			services: require("./images/services.png"),

			// images/icon
			ic_alert: require("./images/icons/ic_alert.png"),
			ic_authorized: require("./images/icons/ic_authorized.png"),
			ic_search: require("./images/icons/ic_email.png"),
			ic_error: require("./images/icons/ic_error.png"),
			ic_key: require("./images/icons/ic_key.png"),
			ic_login: require("./images/icons/ic_login.png"),
			ic_mobile: require("./images/icons/ic_mobile.png"),
			ic_upload: require("./images/icons/ic_upload.png"),
			ic_upload_white: require("./images/icons/ic_upload_white.png"),
			ic_warning: require("./images/icons/ic_warning.png"),
			circle_account: require("./images/icons/ic_account.png"),
			circle_convert: require("./images/icons/ic_convert.png"),
			circle_fund: require("./images/icons/ic_fund.png"),
			circle_mobile: require("./images/icons/ic_mobile_circle.png"),
			circle_points: require("./images/icons/ic_points.png"),
			circle_send: require("./images/icons/ic_send.png"),
			circle_wallet: require("./images/icons/ic_wallet.png"),
			ic_email: require("./images/icons/email_icon.png"),
			ic_search: require("./images/icons/ic_search.png"),

			// images/devices
			mac_dektop: require("./images/devices/mac_dektop.png"),
			windows_dektop: require("./images/devices/windows_dektop.png"),
			android_mobile: require("./images/devices/android_mobile.png"),
			apple_mobile: require("./images/devices/apple_mobile.png"),

			user_icon: require("./images/user_icon.png"),
			background_dark: require("./images/background_dark.png"),
			bg_header: require("./images/bg_header.png"),
			pricecircle: require("./images/pricecircle.png"),
			securecircle: require("./images/securecircle.png"),
			mapcircle: require("./images/mapcircle.png"),
			searchicon: require("./images/search_icon.png"),
			searchiconpress: require("./images/search_icon_press.png"),
			add_new: require("./images/add_new.png"),

			lineanimation: require("./data/LineAnimation.json"),

			// SAMPLE ID
			view_id: require("./images/ids/view_id.png"),
			view_selfie_id: require("./images/ids/view_selfie_id.png"),
			view_utility_bill: require("./images/ids/view_utility_bill.jpg"),
			success: require("./images/ids/modal_success.png"),
			error: require("./images/ids/modal_error.png"),

			// Fundrequest
			bank: require("./images/fundrequest/bank.png"),
			credit_debit: require("./images/fundrequest/credit_debit.png"),
			dragonpay: require("./images/fundrequest/dragonpay.png"),
			process1_active: require("./images/fundrequest/process1_active.png"),
			process2_active: require("./images/fundrequest/process2_active.png"),
			process2_nonactive: require("./images/fundrequest/process2_nonactive.png"),
			process3_active: require("./images/fundrequest/process3_active.png"),
			process3_nonactive: require("./images/fundrequest/process3_nonactive.png"),

			// TICKETING
			dot: require("./images/ticketing/dot.png"),
			baggage: require("./images/ticketing/baggage.png"),
			flight: require("./images/ticketing/flight.png"),
			suitcase: require("./images/ticketing/suitcase.png"),
			place: require("./images/ticketing/place.png"),
			calendar: require("./images/ticketing/calendar.png"),
			ticket: require("./images/ticketing/ticket.png"),
			ticket2: require("./images/ticketing/ticket2.png"),
			AirAsia: require("./images/ticketing/AirAsia.png"),
			PAL: require("./images/ticketing/PAL.png"),
			CP: require("./images/ticketing/CP.png"),
			depart_white: require("./images/ticketing/depart_white.png"),
			return_white: require("./images/ticketing/depart_white.png"),
			Departure: require("./images/ticketing/Departure.png"),
			Return: require("./images/ticketing/Return.png"),
			place_dark: require("./images/ticketing/place_dark.png"),
			info_yellow: require("./images/ticketing/info_yellow.png"),
			cart_white: require("./images/ticketing/cart_white.png"),
			cart_blue: require("./images/ticketing/cart_blue.png"),
			mobile_banner: require("./images/ticketing/mobile_banner.png"),
			INFANT: require("./images/ticketing/toddler.png"),
			CHILD: require("./images/ticketing/child.png"),
			ADULT: require("./images/ticketing/man.png"),
			calendar2: require("./images/ticketing/calendar2.png"),
			account: require("./images/ticketing/account.png"),
			email: require("./images/ticketing/email.png"),
			location: require("./images/ticketing/location.png"),
			bag: require("./images/ticketing/bag.png"),
			seat: require("./images/ticketing/seat.png"),
			meal: require("./images/ticketing/meal.png"),
			travel: require("./images/ticketing/travel.png"),
			nobag: require("./images/ticketing/nobag.png"),
			nobag_active: require("./images/ticketing/nobag_active.png"),
			kg20: require("./images/ticketing/kg20.png"),
			kg20_active: require("./images/ticketing/kg20_active.png"),
			kg25: require("./images/ticketing/kg25.png"),
			kg25_active: require("./images/ticketing/kg25_active.png"),
			kg30: require("./images/ticketing/kg30.png"),
			kg30_active: require("./images/ticketing/kg30_active.png"),
			kg40: require("./images/ticketing/kg40.png"),
			kg40_active: require("./images/ticketing/kg40_active.png"),
			chair_unavailable: require("./images/ticketing/chair_unavailable.png"),
			chair_hot: require("./images/ticketing/chair_hot.png"),
			chair_standard: require("./images/ticketing/chair_standard.png"),
			chair_seat: require("./images/ticketing/chair_seat.png"),
			cardfront: require("./images/ticketing/cardfront.png"),
			cardback: require("./images/ticketing/cardback.png"),
			money: require("./images/ticketing/money.png"),
			money_active: require("./images/ticketing/money_active.png"),
			credit_card: require("./images/ticketing/credit_card.png"),
			credit_card_active: require("./images/ticketing/credit_card_active.png"),
			wallet: require("./images/ticketing/wallet.png"),
			wallet_active: require("./images/ticketing/wallet_active.png"),
			active_bg: require("./images/ticketing/active_bg.png"),
			shop: require("./images/ticketing/shop.png"),

			// STAYCATION ICONS
			ads: require("./images/staycation/ads.png"),
			beach: require("./images/staycation/beach.png"),
			minus: require("./images/staycation/minus.png"),
			plus: require("./images/staycation/plus.png"),
			ic_location: require("./images/staycation/ic_location.png"),
			guest_ads: require("./images/staycation/guest_ads.png"),
			track_bg: require("./images/staycation/track_bg.png"),

			// LOADING
			acash: require("./images/loading/acash.png"),
			cc: require("./images/loading/cc.png"),
			cignal: require("./images/loading/cignal.png"),
			cubizone: require("./images/loading/cubizone.png"),
			eset: require("./images/loading/eset.png"),
			gc: require("./images/loading/gc.png"),
			gm: require("./images/loading/gm.png"),
			gpinoy: require("./images/loading/gpinoy.png"),
			gsat: require("./images/loading/gsat.png"),
			iflix: require("./images/loading/iflix.png"),
			ilw: require("./images/loading/ilw.png"),
			jacks: require("./images/loading/jacks.png"),
			lvlup: require("./images/loading/lvlup.png"),
			marino: require("./images/loading/marino.png"),
			migme: require("./images/loading/migme.png"),
			plp: require("./images/loading/plp.png"),
			rcoin: require("./images/loading/rcoin.png"),
			sky: require("./images/loading/sky.png"),
			softnyx: require("./images/loading/softnyx.png"),
			viu: require("./images/loading/viu.jpg"),
			eload_banner: require("./images/loading/eload_banner.png"),
		};

		this.string = {
			// PHP: "Philippine Wallet",
			// HKD: "Hongkong Wallet",
			// SGD: "Singapore Wallet",
			// AED: "United States Emirate Wallet",
		};

		this.svg = {
			// BOTTOM TABBAR
			Home: <Home />,
		};
	}

	get(name) {
		return this.imgs[name];
	}

	get(name) {
		return this.imgs[name];
	}

	getString(name) {
		return this.string[name];
	}

	getSVG(name) {
		return this.svg[name];
	}
}

const Resource = {
	Color, Elavated, Card,
	ReadMore, Res: ImgResource.getInstance(),
};

export default Resource;
