export const SET_PHONE_SCREEN = "account/types/SET_PHONE_SCREEN";

export const ACCOUNT_SET_MOBILE_INPUT = "account/types/ACCOUNT_SET_MOBILE_INPUT";
export const ACCOUNT_MOBILE_PASSWORD_CORRECT = "account/types/ACCOUNT_MOBILE_PASSWORD_CORRECT";
export const ACCOUNT_MOBILE_TRANSPIN_CORRECT = "account/types/ACCOUNT_MOBILE_TRANSPIN_CORRECT";
export const ACCOUNT_PASSWORD_INCORRECT = "account/types/ACCOUNT_PASSWORD_INCORRECT";
export const ACCOUNT_CHANGE_MOBILE_RESET = "account/types/ACCOUNT_CHANGE_MOBILE_RESET";
export const ACCOUNT_PHONE_CODE_INPROGRESS =
	"account/types/ACCOUNT_PHONE_CODE_INPROGRESS";
export const ACCOUNT_PHONE_CODE_SUCCESS =
	"account/types/ACCOUNT_PHONE_CODE_SUCCESS";
export const ACCOUNT_PHONE_CODE_FAILED =
	"account/types/ACCOUNT_PHONE_CODE_FAILED";
export const ACCOUNT_CHANGE_MOBILE_SUCCESS =
	"account/types/ACCOUNT_CHANGE_MOBILE_SUCCESS";
export const ACCOUNT_CHANGE_MOBILE_FAILED =
	"account/types/ACCOUNT_CHANGE_MOBILE_FAILED";
export const ACCOUNT_CHANGE_MOBILE_INPROGRESS =
	"account/types/ACCOUNT_CHANGE_MOBILE_INPROGRESS";
export const CHECKING_MOBILE_PASSWORD =
	"account/types/CHECKING_MOBILE_PASSWORD";
export const CHECKING_MOBILE_TRANSPIN =
		"account/types/CHECKING_MOBILE_TRANSPIN";
export const ACCOUNT_MOBILE_PASSWORD_INCORRECT =
	"account/types/ACCOUNT_MOBILE_PASSWORD_INCORRECT";
export const ACCOUNT_MOBILE_TRANSPIN_INCORRECT =
		"account/types/ACCOUNT_MOBILE_TRANSPIN_INCORRECT";
export const ACCOUNT_CHANGE_MOBILE_INVALID =
	"account/types/ACCOUNT_CHANGE_MOBILE_INVALID";
export const SENDING_CHANGE_PHONE_CODE =
	"account/types/SENDING_CHANGE_PHONE_CODE";
export const ACCOUNT_CHANGE_PHONE_PROGRESS =
	"account/types/ACCOUNT_CHANGE_PHONE_PROGRESS";
export const ACCOUNT_CHANGE_PHONE_SUCCESS =
	"account/types/ACCOUNT_CHANGE_PHONE_SUCCESS";
export const RESENDING_CHANGE_EMAIL_CODE = "account/types/RESENDING_CHANGE_EMAIL_CODE";
export const RESENDING_CHANGE_EMAIL_CODE_SUCCESS =
	"account/types/RESENDING_CHANGE_EMAIL_CODE_SUCCESS";
export const RESENDING_CHANGE_EMAIL_CODE_FAIL = "account/types/RESENDING_CHANGE_EMAIL_CODE_FAIL";

/* validate new email types */
export const IS_VALIDATING_EMAIL = "account/types/IS_VALIDATING_EMAIL";
export const IS_VALIDATING_EMAIL_DONE = "IS_VALIDATING_EMAIL_DONE";
export const EMAIL_AVAILABLE = "account/types/EMAIL_AVAILABLE";
export const EMAIL_NOT_AVAILABLE = "account/types/EMAIL_NOT_AVAILABLE";
export const VERIFY_EMAIL_RESET = "account/types/VERIFY_EMAIL_RESET";
export const RESET_INPUT_STATE = "account/types/RESET_INPUT_STATE";
export const RESEND_CHANGE_EMAIL_CODE_FAIL = "account/types/RESEND_CHANGE_EMAIL_CODE_FAIL";
export const RESEND_CHANGE_EMAIL_CODE = "account/types/RESEND_CHANGE_EMAIL_CODE";
export const RESEND_CHANGE_EMAIL_CODE_SUCCESS = "account/types/RESEND_CHANGE_EMAIL_CODE_SUCCESS";

/* new email button loader types */
export const BUTTON_LOAD_STOP = "account/types/BUTTON_LOAD_STOP";


/* validate new Phone types */
export const PHONENUMBER_IS_VALIDATING = "account/types/PHONENUMBER_IS_VALIDATING";
export const PHONENUMBER_IS_VALIDATING_DONE = "account/types/PHONENUMBER_IS_VALIDATING_DONE";
export const PHONE_NUMBER_NOT_AVAILABLE = "account/types/PHONE_NUMBER_NOT_AVAILABLE";
export const PHONE_NUMBER_AVAILABLE = "account/types/PHONE_NUMBER_AVAILABLE";
export const RESET_STATE = "account/types/RESET_STATE";
export const PHONE_NUMBER_DATA_RESET = "account/types/PHONE_NUMBER_DATA_RESET";

/* change password types */
export const ACCOUNT_SET_PASSWORD_INPUT = "account/types/ACCOUNT_SET_PASSWORD_INPUT";
export const RESET_PASSWORD_STATE = "account/types/RESET_PASSWORD_STATE";
export const ACCOUNT_CHANGE_PASSWORD_RESET = "account/types/ACCOUNT_CHANGE_PASSWORD_RESET";
export const ACCOUNT_CHANGE_PASSWORD_INPROGRESS =
	"account/types/ACCOUNT_CHANGE_PASSWORD_INPROGRESS";
export const ACCOUNT_CHANGE_PASSWORD_SUCCESS =
	"account/types/ACCOUNT_CHANGE_PASSWORD_SUCCESS";
export const ACCOUNT_CHANGE_PASSWORD_FAILED =
	"account/types/ACCOUNT_CHANGE_PASSWORD_FAILED";
export const ACCOUNT_CHANGE_PASSWORD_INCORRECT_PASS =
	"account/types/ACCOUNT_CHANGE_PASSWORD_INCORRECT_PASS";
export const ACCOUNT_CHANGE_PASSWORD_USERINFO_PROGRESS =
	"account/types/ACCOUNT_CHANGE_PASSWORD_USERINFO_PROGRESS";
export const ACCOUNT_CHANGE_PASSWORD_USERINFO_SUCCESS =
	"account/types/ACCOUNT_CHANGE_PASSWORD_USERINFO_SUCCESS";
export const ACCOUNT_CHANGE_PASSWORD_SAVE_RADIO =
	"account/types/ACCOUNT_CHANGE_PASSWORD_SAVE_RADIO";
export const ACCOUNT_CHANGE_PASS_SENDING_CODE =
	"account/types/ACCOUNT_CHANGE_PASS_SENDING_CODE";
export const ACCOUNT_CHANGE_PASSSWORD_PROGRESS =
	"account/types/ACCOUNT_CHANGE_PASSSWORD_PROGRESS";
export const ACCOUNT_CHANGE_PASS_CODE_INVALID =
	"account/types/ACCOUNT_CHANGE_PASS_CODE_INVALID";
export const ACCOUNT_CHANGE_PASS_SENDING_CODE_FAILED =
	"account/types/ACCOUNT_CHANGE_PASS_SENDING_CODE_FAILED";
export const ACCOUNT_CHANGE_PASSWORD_CODE =
	"account/types/ACCOUNT_CHANGE_PASSWORD_CODE";
export const ACCOUNT_CHANGE_PASSWORD_USERINFO_FAILED =
	"account/types/ACCOUNT_CHANGE_PASSWORD_USERINFO_FAILED";
export const ACCOUNT_CHECK_PASSWORD_SUCCESS =
	"account/types/ACCOUNT_CHECK_PASSWORD_SUCCESS";
export const ACCOUNT_CHANGE_PASS_INCORRECT_NEWPASS =
	"account/types/ACCOUNT_CHANGE_PASS_INCORRECT_NEWPASS";
export const ACCOUNT_CHANGE_PASS_SUCCESS_NEWPASS =
	"account/types/ACCOUNT_CHANGE_PASS_SUCCESS_NEWPASS";


/* change transpin types */
export const ACCOUNT_SET_TRANSACTIONPIN_INPUT = "account/types/ACCOUNT_SET_TRANSACTIONPIN_INPUT";
export const RESET_TRANSACTIONPIN_STATE = "account/types/RESET_TRANSACTIONPIN_STATE";
export const ACCOUNT_CHANGE_TRANSACTIONPIN_RESET = "account/types/ACCOUNT_CHANGE_TRANSACTIONPIN_RESET";
export const ACCOUNT_CHANGE_TRANSACTIONPIN_INPROGRESS = "account/types/ACCOUNT_CHANGE_TRANSACTIONPIN_INPROGRESS";
export const ACCOUNT_CHANGE_TRANSACTIONPIN_SUCCESS = "account/types/ACCOUNT_CHANGE_TRANSACTIONPIN_SUCCESS";
export const ACCOUNT_CHANGE_TRANSACTIONPIN_FAILED = "account/types/ACCOUNT_CHANGE_TRANSACTIONPIN_FAILED";
export const ACCOUNT_CHANGE_TRANSACTIONPIN_INCORRECT_PASS = "account/types/ACCOUNT_CHANGE_TRANSACTIONPIN_INCORRECT_PASS";
export const ACCOUNT_CHANGE_TRANSACTIONPIN_USERINFO_PROGRESS = "account/types/ACCOUNT_CHANGE_TRANSACTIONPIN_USERINFO_PROGRESS";
export const ACCOUNT_CHANGE_TRANSACTIONPIN_USERINFO_SUCCESS = "account/types/ACCOUNT_CHANGE_TRANSACTIONPIN_USERINFO_SUCCESS";
export const ACCOUNT_CHANGE_TRANSACTIONPIN_SAVE_RADIO = "account/types/ACCOUNT_CHANGE_TRANSACTIONPIN_SAVE_RADIO";
export const ACCOUNT_CHANGE_TRANSACTIONPIN_SENDING_CODE = "account/types/ACCOUNT_CHANGE_TRANSACTIONPIN_SENDING_CODE";
export const ACCOUNT_CHANGE_TRANSACTIONPIN_PROGRESS = "account/types/ACCOUNT_CHANGE_TRANSACTIONPIN_PROGRESS";
export const ACCOUNT_CHANGE_TRANSACTIONPIN_CODE_INVALID = "account/types/ACCOUNT_CHANGE_TRANSACTIONPIN_CODE_INVALID";
export const ACCOUNT_CHANGE_TRANSACTIONPIN_SENDING_CODE_FAILED = "account/types/ACCOUNT_CHANGE_TRANSACTIONPIN_SENDING_CODE_FAILED";
export const ACCOUNT_CHANGE_TRANSACTIONPIN_CODE = "account/types/ACCOUNT_CHANGE_TRANSACTIONPIN_CODE";
export const ACCOUNT_CHANGE_TRANSACTIONPIN_USERINFO_FAILED = "account/types/ACCOUNT_CHANGE_TRANSACTIONPIN_USERINFO_FAILED";
export const ACCOUNT_CHECK_TRANSACTIONPIN_SUCCESS = "account/types/ACCOUNT_CHECK_TRANSACTIONPIN_SUCCESS";
export const ACCOUNT_CHANGE_TRANSACTIONPIN_INCORRECT_NEWTRANSACTIONPIN = "account/types/ACCOUNT_CHANGE_TRANSACTIONPIN_INCORRECT_NEWTRANSACTIONPIN";
export const ACCOUNT_CHANGE_TRANSACTIONPIN_SUCCESS_NEWTRANSACTIONPIN = "account/types/ACCOUNT_CHANGE_TRANSACTIONPIN_SUCCESS_NEWTRANSACTIONPIN";


/* change email types */
export const SET_EMAIL_SCREEN = "account/types/SET_EMAIL_SCREEN";
export const ACCOUNT_SET_EMAIL_INPUT = "account/types/ACCOUNT_SET_EMAIL_INPUT";
export const ACCOUNT_CHANGE_EMAIL_RESET = "account/types/ACCOUNT_CHANGE_EMAIL_RESET";
export const ACCOUNT_EMAIL_CODE_INPROGRESS = "account/types/ACCOUNT_EMAIL_CODE_INPROGRESS";
export const ACCOUNT_EMAIL_CODE_SUCCESS =
	"account/types/ACCOUNT_EMAIL_CODE_SUCCESS";
export const ACCOUNT_EMAIL_CODE_FAILED =
	"account/types/ACCOUNT_EMAIL_CODE_FAILED";
export const ACCOUNT_CHANGE_EMAIL_INCORRECT_PASS =
	"account/types/ACCOUNT_CHANGE_EMAIL_INCORRECT_PASS";
export const ACCOUNT_CHANGE_EMAIL_INCORRECT_TRANSPIN =
	"account/types/ACCOUNT_CHANGE_EMAIL_INCORRECT_TRANSPIN";
export const ACCOUNT_CHANGE_EMAIL_SUCCESS =
	"account/types/ACCOUNT_CHANGE_EMAIL_SUCCESS";
export const ACCOUNT_CHANGE_EMAIL_INPROGRESS =
	"account/types/ACCOUNT_CHANGE_EMAIL_INPROGRESS";
export const ACCOUNT_CHANGE_EMAIL_FAILED =
	"account/types/ACCOUNT_CHANGE_EMAIL_FAILED";
export const CHECKING_EMAIL_PASSWORD =
	"account/types/CHECKING_EMAIL_PASSWORD";
export const CHECKING_EMAIL_TRANSPIN =
		"account/types/CHECKING_EMAIL_TRANSPIN";
export const ACCOUNT_CHANGE_EMAIL_PROGRESS =
	"account/types/ACCOUNT_CHANGE_EMAIL_PROGRESS";
export const SENDING_CHANGE_EMAIL_CODE =
	"account/types/SENDING_CHANGE_EMAIL_CODE";
export const SEND_CHANGE_EMAIL_CODE_FAILED =
	"account/types/SEND_CHANGE_EMAIL_CODE_FAILED";
export const ACCOUNT_CHANGE_EMAIL_INVALID =
	"account/types/ACCOUNT_CHANGE_EMAIL_INVALID";
export const ACCOUNT_EMAIL_PASSWORD_CORRECT = "account/types/ACCOUNT_EMAIL_PASSWORD_CORRECT";
export const ACCOUNT_EMAIL_TRANSPIN_CORRECT = "account/types/ACCOUNT_EMAIL_TRANSPIN_CORRECT";


export const SET_ACCOUNT_SCREEN = "account/type/SET_ACCOUNT_SCREEN";
export const SET_CHANGE_PASSWORD_SCREEN = "account/types/SET_CHANGE_PASSWORD_SCREEN";
export const SET_CHANGE_TRANSACTIONPIN_SCREEN = "account/types/SET_CHANGE_TRANSACTIONPIN_SCREEN";


/* ------ SECURITY SETTINGS TYPES -------- */
/* CHANGE 2FA SETTING TYPESS */
export const SETTING_CHANGE_2FA_SUCCESS = "setting/types/SETTING_CHANGE_2FA_SUCCESS";
export const SETTING_CHANGE_2FA_INPROGRESS = "setting/types/SETTING_CHANGE_2FA_INPROGRESS";
export const SETTING_CHANGE_2FA_FAILED = "settings/types/SETTING_CHANGE_2FA_FAILED";

/* ALERTS */
export const SETTING_LOGIN_ALERT_SUCCESS = "settings/types/SETTING_LOGIN_ALERT_SUCCESS";
export const SETTING_LOGIN_ALERT_EMAILINPROGRESS =
	"settings/types/SETTING_LOGIN_ALERT_EMAILINPROGRESS";
export const SETTING_LOGIN_ALERT_SMSINPROGRESS =
	"settings/types/SETTING_LOGIN_ALERT_SMSINPROGRESS";
export const ENABLE_LOGIN_ALERT_EMAILINPROGRESS =
	"settings/types/ENABLE_LOGIN_ALERT_EMAILINPROGRESS";
export const ENABLE_LOGIN_ALERT_EMAIL_SUCCESS =
	"settings/types/ENABLE_LOGIN_ALERT_EMAIL_SUCCESS";
export const ENABLE_LOGIN_ALERT_EMAIL_FAILED =
	"settings/types/ENABLE_LOGIN_ALERT_EMAIL_FAILED";
export const ENABLE_LOGIN_ALERT_SMSINPROGRESS =
	"settings/types/ENABLE_LOGIN_ALERT_SMSINPROGRESS";
export const ENABLE_LOGIN_ALERT_SMS_SUCCESS =
	"settings/types/ENABLE_LOGIN_ALERT_SMS_SUCCESS";
export const ENABLE_LOGIN_ALERT_SMS_FAILED =
	"settings/types/ENABLE_LOGIN_ALERT_SMS_FAILED";

/* WHERE YOU LOGGED IN */
export const SETTING_HISTORY_SUCCESS = "setting/types/SETTING_HISTORY_SUCCESS";
export const SETTING_HISTORY_SEE_MORE = "setting/types/SETTING_HISTORY_SEE_MORE";
export const SETTING_HISTORY_RESET = "setting/types/SETTING_HISTORY_RESET";
export const SETTING_HISTORY_FAILED = "setting/types/SETTING_HISTORY_FAILED";
export const SETTING_DEVICE_INPROGRESS = "setting/types/SETTING_DEVICE_INPROGRESS";
export const SETTING_DEVICE_SUCCESS = "setting/types/SETTING_DEVICE_SUCCESS";
export const SETTING_DEVICE_FAILED = "setting/types/SETTING_DEVICE_FAILED";
export const SETTING_DEVICE_REMOVED = "setting/types/SETTING_DEVICE_REMOVED";
export const SELECTED_DEVICE_TO_REMOVE = "setting/types/SELECTED_DEVICE_TO_REMOVE";

// set profile screen
export const SET_CURRENT_SCREEN = "profile/types/SET_CURRENT_SCREEN";

export const LOGOUT = "logout/types/LOGOUT";
