import { StyleSheet} from "react-native";
import {getStatusBarHeight} from "__src/resources/customize/StatusBarHeight";
import Resource from "__src/resources";
const {Color} = Resource;

export default StyleSheet.create({
	container: {flexShrink: 1, width: "100%", height: "100%", backgroundColor: Color.StatusBar},
	bg: {position: "absolute", flex: 1, backgroundColor: Color.white, marginTop: getStatusBarHeight(true)},
	account: {backgroundColor: "blue", marginTop: getStatusBarHeight(true)},
	body: {flex: 1, backgroundColor: Color.bg},
	wallet: {position: "absolute", zIndex: 1},
	services: {width: "100%", backgroundColor: "transparent"},

	btnWrapper: {flexShrink: 1, borderRadius: 5, backgroundColor: Color.colorPrimary},

	flex1: {flex: 1},
	flexShrink1: {flexShrink: 1},
	flex1marT15: {flex: 1},
	flex1marT20: {flex: 1, marginTop: 20},
	flex1marV20: {flex: 1, marginVertical: 20},
	flex1allCenter: {flexShrink: 1, alignItems: "center", justifyContent: "center"},
	flex1padH20: {flex: 1, paddingHorizontal: 20},
	flex1marT30padH20: {flex: 1, paddingHorizontal: 20, marginTop: 20},
	marT10: {marginTop: 10},
	marT15: {marginTop: 15},
	marT20: {marginTop: 20},
	marT30: {marginTop: 30},
	marB10: {marginBottom: 10},
	marB20: {marginBottom: 20},
	imgsuccess: {width: 125, height: 125, alignSelf: "center", marginVertical: 10},
	img35: {width: 35, height: 35},
	txtsuccess: {textAlign: "center", fontFamily: "Roboto-Light", color: Color.green, fontSize: 14, marginTop: 15},
	dlWrapper: {flexDirection: "column", justifyContent: "center", alignItems: "center", marginBottom: 30},
	labelStyle2: {color: Color.black, fontWeight: "bold"},
	txtDownload: {color: Color.LightBlue, fontFamily: "Roboto-Light", fontSize: 13},

	// EcashtoEcash.js
	ecashContainer: {flex: 1,  backgroundColor: Color.bg},
	txtError: {color: Color.red, fontSize: 13, fontWeight: "normal", fontFamily: "Roboto-Light", marginTop: 4},
	flatlist: {paddingHorizontal: 20},
	loadView: {width: 10, height: 10},
	qrImage: {width: 22, height: 22, padding: 10},
	renderBaseWrapper: {flexDirection: "row", width: "100%", height: 40, alignItems: "center",  borderBottomColor: "#404040", borderBottomWidth: 0.6},
	txtInput: {flex: 1, fontFamily: "Roboto-Light", fontSize: 14, paddingVertical: 0},
	renderBaseImg: {width: 20, height: 20},
	renderRowWrapper: {paddingHorizontal: 10, flexDirection: "row", height: 40, alignItems: "center", justifyContent: "space-between", backgroundColor: "white"},
	renderRowText: {margin: 4, fontSize: 12, color: Color.Standard2, fontFamily: "Roboto-Light", textAlignVertical: "center"},
	viewDivider: {height: 0.5, backgroundColor: Color.Standard, marginTop: 8},
	modalWrapper: {flexShrink: 1, justifyContent: "center", width: "100%",
		height: "100%", paddingHorizontal: 25, paddingVertical: "10%", backgroundColor: "rgba(0, 0, 0, 0.5)"},
	modalWrapper2: {backgroundColor: "#fff", padding: 20},
	title: {color: Color.Standard2, fontFamily: "Roboto-Light", fontSize: 20},
	subtitle: {color: Color.Standard, fontFamily: "Roboto-Light", fontSize: 15},
	subtitle2: {color: Color.Standard, fontFamily: "Roboto-Light", fontSize: 14},
	subtitle3: {color: Color.Standard2, fontFamily: "Roboto-Light", fontSize: 14},
	txtInstruction: {color: Color.Standard2, fontFamily: "Roboto-Light", fontSize: 14, marginVertical: 10},

	amount: {color: Color.Standard2, fontWeight: "bold"},
	value: {color: Color.Standard2, fontWeight: "bold"},
	valueStatus: {color: Color.LightBlue, fontFamily: "Roboto-Light" },
	valuePayment: {color: Color.Standard2, fontFamily: "Roboto-Light", textAlign: "left" },
	valuePayment2: {color: Color.Standard2, fontFamily: "Roboto-Light", fontWeight: "bold", textAlign: "left" },
	modalWrapper3: {width: "100%", flexDirection: "row", justifyContent: "flex-end", marginTop: 40},
	modalBtn: {flex: 1, borderColor: Color.colorPrimary, borderWidth: 0.5,
		backgroundColor: Color.white, marginRight: 5},
	width120: {flex: 1, marginLeft: 5},
	renderSuccessWrapper: {flex: 1, padding: 30, flexDirection: "column", justifyContent: "space-between"},
	txt1: {textAlign: "center", fontFamily: "Roboto-Light", color: Color.Standard2, fontSize: 20},
	txt2: {textAlign: "center", fontFamily: "Roboto-Light", color: Color.Standard2, fontSize: 21, fontWeight: "700"},
	txt3: {textAlign: "center", fontFamily: "Roboto-Light", color: Color.Standard2, fontSize: 13},
	txt3_1: {textAlign: "center", fontFamily: "Roboto-Light", color: Color.Standard2, fontSize: 13, marginTop: 20},
	txt4: {textAlign: "center", fontFamily: "Roboto-Light", color: Color.Standard2, fontSize: 15, fontWeight: "700"},
	txtok: {color: Color.colorPrimary, fontSize: 18, alignSelf: "center", paddingHorizontal: 30, paddingVertical: 10},
	renderSuccessWrapper2: {justifyContent: "center", alignItems: "center", marginBottom: 20},
	txtLabel: {color: Color.Standard, fontSize: 14, fontFamily: "Roboto-Light"},
	viewTarget: {flexDirection: "row", width: "100%", height: 40, alignItems: "center", paddingRight: 5,  borderBottomColor: "#404040", borderBottomWidth: 0.6},
	viewReason: {flexDirection: "row", width: "100%", height: 60,  borderBottomColor: "#404040", borderBottomWidth: 0.6},
	txtConvertAmt: {textAlign: "right", fontFamily: "Roboto", fontSize: 15, color: Color.Standard2, marginTop: 15},
	btnProceed: {marginHorizontal: 20, borderBottomWidth: 6, marginBottom: 10},
	targetDropdown: { height: 150},
	txtCode: {fontSize: 10, color: Color.Standard, marginTop: 5},
	txtNote: {color: Color.red, fontSize: 13, fontWeight: "normal", fontFamily: "Roboto-Light", marginTop: 4},
	walletWrapper: {flexDirection: "row", justifyContent: "space-between", backgroundColor: Color.gray06,
		padding: 20, alignItems: "center"},
	flexColumn: {width: "60%", flexDirection: "column"},
	walletTxtSource: {fontFamily: "Roboto-Light", fontSize: 17, color: Color.Standard2},
	walletTxtSourceValue: {fontFamily: "Roboto", fontSize: 17, color: Color.colorPrimaryDark},
	walletTxtSourceWallet: {fontFamily: "Roboto-Light", fontSize: 17, color: Color.Standard2, marginTop: 10},
	walletTxtSourceWalletValue: {fontFamily: "Roboto", fontSize: 17, color: Color.colorPrimaryDark},
	walletTxtSourceWalletValue2: {fontSize: 13, color: Color.Standard},
	walletTxtAccountType: {width: "40%", fontFamily: "Roboto-Light", fontSize: 14, color: Color.Standard, textAlign: "center"},

	// Fundrequest - Deposit
	inputStyles: {fontSize: 18, color: Color.Standard2},
	borderWidth0: {borderBottomWidth: 0},
	btnStyle: {width: 100, height: 40, alignSelf: "flex-end", borderBottomWidth: 5, marginBottom: 20, marginTop: 20},
	btnStyle2: {width: "100%", height: 40, alignSelf: "flex-end", borderBottomWidth: 5 },
	btnStyle3: {width: "100%", height: 40, alignSelf: "flex-end", backgroundColor: "transparent", borderBottomWidth: 0, borderColor: "transparent" },
	btnLabelStyle: {color: Color.colorPrimaryDark},
	bankWrapper1: {flex: 1, marginTop: 10, backgroundColor: Color.bg},
	bankWrapper2: {height: "50%", paddingHorizontal: 20},
	bankWrapper3: {height: "50%", paddingHorizontal: 20, backgroundColor: Color.gray06},
	otpBottom: {flexDirection: "row", justifyContent: "flex-end", marginBottom: 20, marginTop: 10},
	btnback: {width: 120, borderColor: Color.colorPrimaryDark, borderWidth: 0.5,
		backgroundColor: Color.white, marginRight: 10},
	width1202: {width: 120},
	fontWBold: {fontWeight: "bold"},

	// Fundrequest - BankDepositConfirm
	flex1padH20marT10: {flex: 1, paddingHorizontal: 20, marginTop: 10},
	wrapper1: {flexShrink: 1, backgroundColor: Color.Header, borderRadius: 5,
		marginHorizontal: 5, marginTop: 10},
	imgFile: {width: 270, height: 180, alignSelf: "center"},
	btnInfo: {position: "absolute", top: 0, right: 0},
	padmar0: {padding: 0, margin: 0},
	btnCamera: {position: "absolute", justifyContent: "center", alignItems: "center", flexDirection: "row", width: "100%",
	 height: 50, bottom: 0, backgroundColor: Color.red01,
	 borderBottomEndRadius: 5, borderBottomStartRadius: 5, opacity: 0.9},
	txtCamera: {textAlign: "center", fontFamily: "Roboto-Light", color: Color.white, fontSize: 16,
		marginLeft: 7},
	txtOR: {textAlign: "center", fontFamily: "Roboto-Light", color: Color.Standard2, fontSize: 10, marginTop: 10},
	btnClickToUpload: {flexDirection: "row", justifyContent: "center", alignItems: "center"},
	imgUpload: {width: 23, height: 23, alignSelf: "center"},
	txtUpload: {textAlign: "center", fontFamily: "Roboto-Light", color: Color.LightBlue, fontSize: 13,
		marginLeft: 7, textDecorationLine: "underline"},
	btnFileUpload: {flexDirection: "row", padding: 5, borderRadius: 3, backgroundColor: Color.LightBlue },
	txtUploadFile: {fontFamily: "Roboto-Light", color: Color.white, fontSize: 13, marginLeft: 7},
	labelStyle: {color: Color.Standard, fontSize: 14, fontFamily: "Roboto-Light"},
	renderBase: {flexDirection: "row", width: "100%", height: 40, alignItems: "center",  borderBottomColor: "#404040", borderBottomWidth: 0.6},
	renderRow: {paddingHorizontal: 10, flexDirection: "row", height: 40, alignItems: "center", justifyContent: "space-between", backgroundColor: "white"},
	renderRowTxt: {margin: 4, fontSize: 12, color: Color.Standard2, fontFamily: "Roboto-Light", textAlignVertical: "center"},
	input: {flex: 1, fontFamily: "Roboto-Light", fontSize: 14},
	customStyle: {backgroundColor: Color.Header, opacity: 0.3, zIndex: 1, position: "absolute", top: 0, bottom: 0, left: 0, right: 0},
	errStyle: {color: Color.red, fontSize: 13, fontWeight: "normal", fontFamily: "Roboto-Light", marginTop: 4},

	// Add wallet
	txtTitle: {fontSize: 25, fontFamily: "Roboto-Light", color: Color.Standard2},
	txtSubtitle: {color: Color.Standard, marginTop: 5},
	dropDownStyle: {height: 250},
	btnCreate: {marginHorizontal: 30, borderBottomWidth: 6, marginBottom: 5},
	btnCancel: {backgroundColor: Color.transparent, color: Color.colorPrimaryDark,
		 marginHorizontal: 30, borderBottomWidth: 0, marginBottom: 10},
	addTxtNote: {textAlign: "center", fontFamily: "Roboto-Light", color: Color.Standard2, fontSize: 24},
	addTxtSuccess: {textAlign: "center", fontFamily: "Roboto-Light", color: Color.Standard2, fontSize: 25, fontWeight: "700"},
	highlighted: {fontWeight: "bold"},
	img1: {width: 180, height: 180, alignSelf: "center", marginVertical: 10},

	// Conversion
	conRenderBase: {flexShrink: 1, marginLeft: 5, flexDirection: "row", height: 40, alignItems: "center" },
	conRBImg: {width: 22, height: 22},
	conRBTxt1: {marginLeft: 5, fontFamily: "Roboto-Light", fontSize: 14, color: Color.Standard2},
	conRBTxt2: {marginLeft: 5, fontFamily: "Roboto-Light", fontSize: 14, color: Color.white},
	conRenderRow: {paddingLeft: 7, flexDirection: "row", height: 40, alignItems: "center", justifyContent: "flex-start", backgroundColor: "white"},
	conRRImg: {width: 22, height: 22},
	conRRTxt: {margin: 4, fontSize: 13, color: Color.Standard, fontFamily: "Roboto", textAlignVertical: "center"},
	conCard: {height: "65%", borderRadius: 5},
	conView1: {backgroundColor: Color.Header, padding: 20, paddingTop: 30,
		borderTopRightRadius: 5, borderTopLeftRadius: 5},
	conView2: {flex: 1, backgroundColor: Color.white, padding: 20, paddingTop: 25,
		borderBottomEndRadius: 5, borderBottomStartRadius: 5, zIndex: 3},
	conView3: {flex: 1, alignItems: "flex-end"},
	conView4: {marginHorizontal: 30, alignItems: "center"},
	conView5: { width: "100%", height: 0.7, backgroundColor: Color.Standard2, marginVertical: 5},
	conView6: {flexGrow: 1, alignItems: "center", justifyContent: "center"},
	flexRow: {flexDirection: "row"},
	flexCol: {flexDirection: "column"},
	conImgSwitch: {width: 30, height: 25},
	conBtnSwitch: {position: "absolute", left: 18, zIndex: 10, elevation: 3},
	contxt1: {color: Color.Standard2, fontFamily: "Roboto-Light", fontSize: 16},
	contxt2: {color: Color.white, fontFamily: "Roboto-Light", fontSize: 16},
	contxt3: {alignSelf: "flex-end", color: Color.white, fontFamily: "Roboto-Light", fontSize: 14 },
	contxt4: {flex: 1, color: Color.LightBlue, fontFamily: "Roboto-Light", fontSize: 22, fontWeight: "bold", textAlign: "right", marginTop: 25},
	contxt5: {flexGrow: 1, textAlign: "right", color: Color.Standard2, fontFamily: "Roboto-Light", fontSize: 14 },
	contxt6: {color: Color.Header, fontFamily: "Roboto-Light", fontSize: 14, fontWeight: "bold" },
	contxt7: {color: Color.colorPrimary, fontFamily: "Roboto-Light", fontSize: 14, fontWeight: "bold" },
	contxt8: {textAlign: "center", marginTop: 10, color: Color.Standard2, fontSize: 12, fontFamily: "Roboto-Light", paddingHorizontal: 10},
	contxt9: {textAlign: "center", backgroundColor: Color.lightred, padding: 10, color: Color.red, fontSize: 12, fontFamily: "Roboto-Light"},
	contxtInput: {flex: 1, color: Color.colorPrimary, fontFamily: "Roboto-Light", fontSize: 22, fontWeight: "bold", textAlign: "right", marginTop: 15, marginRight: 3},
	condropdown: {height: 150, width: 70},
	conBtnConvert: {borderBottomWidth: 6},

	// UNIFIED STORE
	unifiedView1: {flexDirection: "row", width: "60%", height: 40, alignItems: "center", alignSelf: "center", paddingRight: 5, borderRadius: 5,  borderColor: "#404040", borderWidth: 0.6},
	unifiedWrapper2: {height: "35%", paddingHorizontal: 20},
	unifiedWrapper3: {height: "65%", paddingHorizontal: 20, backgroundColor: Color.gray06},
	txtAmount: {flex: 1, fontFamily: "Roboto-Light", fontSize: 14, paddingVertical: 0, marginLeft: 5},
	txt5: {textAlign: "center", fontSize: 18, fontFamily: "Roboto-Light", marginTop: 10},
});
