export const SET_CHANGE_PROFILE_INPUTS = "profile/types/SET_CHANGE_PROFILE_INPUTS";
export const RESET_CHANGE_PROFILE_INPUTS = "profile/types/RESET_CHANGE_PROFILE_INPUTS";
export const IS_SAVING_PROFILE_CHANGES = "profile/types/IS_SAVING_PROFILE_CHANGES";
export const DONE_SAVING_PROFILE_CHANGES = "profile/types/DONE_SAVING_PROFILE_CHANGES";
export const FAIL_SAVING_PROFILE_CHANGES = "profile/types/FAIL_SAVING_PROFILE_CHANGES";

export const LOGIN_SUCCESS = "login/types/LOGIN_SUCCESS";
export const LOGOUT = "logout/types/LOGOUT";
export const SET_VERIFICATION_MAIN_SCREEN = "account/types/SET_VERIFICATION_MAIN_SCREEN";

// change profile photo

export const IS_UPLOADING_PROFILE_PHOTO = "profile/types/IS_UPLOADING_PROFILE_PHOTO";
export const DONE_UPLOADING_PROFILE_PHOTO = "profile/types/DONE_UPLOADING_PROFILE_PHOTO";
export const FAIL_UPLOADING_PROFILE_PHOTO = "profile/types/FAIL_UPLOADING_PROFILE_PHOTO";
export const IS_UPDATING_PROFILE_PHOTO = "profile/types/IS_UPDATING_PROFILE_PHOTO";
export const DONE_UPDATING_PROFILE_PHOTO = "profile/types/DONE_UPDATING_PROFILE_PHOTO";
export const FAIL_UPDATING_PROFILE_PHOTO = "profile/types/FAIL_UPDATING_PROFILE_PHOTO";
export const RESET_UPDATING_PROFILE_PHOTO = "profile/types/RESET_UPDATING_PROFILE_PHOTO";
export const PROFILE_VERIFICATION_IS_CLICK = "profile/types/PROFILE_VERIFICATION_IS_CLICK";

export const RESET_ADDRESS_VERIFY = "profile/types/RESET_ADDRESS_VERIFY";
export const SAME_STATE_FOR_SELFIE_ADDRESS = "profile/types/SAME_STATE_FOR_SELFIE_ADDRESS";
export const SAVE_QR_CODE = "profile/types/SAVE_QR_CODE";

// new account verification
export const CHECK_VERIFY_ID = "profile/types/CHECK_VERIFY_ID";

export const ADDITIONAL_DETAILS = "login/types/ADDITIONAL_DETAILS";

export const IS_SENDING_EMAIL_VERIFICATION_CODE =
	"profile/types/IS_SENDING_EMAIL_VERIFICATION_CODE";
export const DONE_SENDING_EMAIL_VERIFICATION_CODE =
	"profile/types/DONE_SENDING_EMAIL_VERIFICATION_CODE";
export const FAIL_SENDING_EMAIL_VERIFICATION_CODE =
	"profile/types/FAIL_SENDING_EMAIL_VERIFICATION_CODE";
export const IS_VERIFYING_EMAIL = "profile/types/IS_VERIFYING_EMAIL";
export const DONE_VERIFYING_EMAIL = "profile/types/DONE_VERIFYING_EMAIL";
export const FAIL_VERIFYING_EMAIL = "profile/types/FAIL_VERIFYING_EMAIL";
export const IS_SENDING_MOBILE_VERIFICATION_CODE =
	"profile/types/IS_SENDING_MOBILE_VERIFICATION_CODE";
export const DONE_SENDING_MOBILE_VERIFICATION_CODE =
	"profile/types/DONE_SENDING_MOBILE_VERIFICATION_CODE";
export const FAIL_SENDING_MOBILE_VERIFICATION_CODE =
	"profile/types/FAIL_SENDING_MOBILE_VERIFICATION_CODE";
export const IS_VERIFYING_MOBILE = "profile/types/IS_VERIFYING_MOBILE";
export const DONE_VERIFYING_MOBILE = "profile/types/DONE_VERIFYING_MOBILE";
export const FAIL_VERIFYING_MOBILE = "profile/types/FAIL_VERIFYING_MOBILE";
export const IS_SUBMITTING_KYC = "profile/types/IS_SUBMITTING_KYC";
export const DONE_SUBMITTING_KYC = "profile/types/DONE_SUBMITTING_KYC";
export const FAIL_SUBMITTING_KYC = "profile/types/FAIL_SUBMITTING_KYC";
export const IS_UPLOADING_ID_PHOTO = "profile/types/IS_UPLOADING_ID_PHOTO";
export const DONE_UPLOADING_ID_PHOTO = "profile/types/DONE_UPLOADING_ID_PHOTO";
export const RESET_UPLOADING_ID_PHOTO = "profile/types/RESET_UPLOADING_ID_PHOTO";
export const IS_UPLOADING_SELFIE_PHOTO = "profile/types/IS_UPLOADING_SELFIE_PHOTO";
export const DONE_UPLOADING_SELFIE_PHOTO = "profile/types/DONE_UPLOADING_SELFIE_PHOTO";
export const RESET_UPLOADING_SELFIE_PHOTO = "profile/types/RESET_UPLOADING_SELFIE_PHOTO";
export const IS_VERIFYING_UPLOAD_ID_SELFIE_PHOTO =
	"profile/types/IS_VERIFYING_UPLOAD_ID_SELFIE_PHOTO";
export const DONE_VERIFYING_UPLOAD_ID_SELFIE_PHOTO =
	"profile/types/DONE_VERIFYING_UPLOAD_ID_SELFIE_PHOTO";
export const FAIL_VERIFYING_UPLOAD_ID_SELFIE_PHOTO =
	"profile/types/FAIL_VERIFYING_UPLOAD_ID_SELFIE_PHOTO";
export const RESET_VERIFYING_UPLOAD_ID_SELFIE_PHOTO =
	"profile/types/RESET_VERIFYING_UPLOAD_ID_SELFIE_PHOTO";
export const IS_UPLOADING_ADDRESS_PHOTO = "profile/types/IS_UPLOADING_ADDRESS_PHOTO";
export const DONE_UPLOADING_ADDRESS_PHOTO = "profile/types/DONE_UPLOADING_ADDRESS_PHOTO";
export const RESET_UPLOADING_ADDRESS_PHOTO = "profile/types/RESET_UPLOADING_ADDRESS_PHOTO";
export const IS_UPLOADING_AUTH_PHOTO = "profile/types/IS_UPLOADING_AUTH_PHOTO";
export const DONE_UPLOADING_AUTH_PHOTO = "profile/types/DONE_UPLOADING_AUTH_PHOTO";
export const RESET_UPLOADING_AUTH_PHOTO = "profile/types/RESET_UPLOADING_AUTH_PHOTO";
export const IS_VERIFYING_UPLOAD_ADDRESS_AUTH_PHOTO =
	"profile/types/IS_VERIFYING_UPLOAD_ADDRESS_AUTH_PHOTO";
export const DONE_VERIFYING_UPLOAD_ADDRESS_AUTH_PHOTO =
	"profile/types/DONE_VERIFYING_UPLOAD_ADDRESS_AUTH_PHOTO";
export const FAIL_VERIFYING_UPLOAD_ADDRESS_AUTH_PHOTO =
	"profile/types/FAIL_VERIFYING_UPLOAD_ADDRESS_AUTH_PHOTO";
export const RESET_VERIFYING_UPLOAD_ADDRESS_AUTH_PHOTO =
	"profile/types/RESET_VERIFYING_UPLOAD_ADDRESS_AUTH_PHOTO";
export const CHANGE_CURRENT_STEP = "profile/types/CHANGE_CURRENT_STEP";
export const SET_CURRENT_SCREEN = "profile/types/SET_CURRENT_SCREEN";
export const IS_CLEARING_ID_SELFIE_PHOTO = "profile/types/IS_CLEARING_ID_SELFIE_PHOTO";
export const DONE_CLEARING_ID_SELFIE_PHOTO = "profile/types/DONE_CLEARING_ID_SELFIE_PHOTO";
export const FAIL_CLEARING_ID_SELFIE_PHOTO = "profile/types/FAIL_CLEARING_ID_SELFIE_PHOTO";
export const IS_CLEARING_PROOF_OF_ADDRESS_PHOTO =
	"profile/types/IS_CLEARING_PROOF_OF_ADDRESS_PHOTO";
export const DONE_CLEARING_PROOF_OF_ADDRESS_PHOTO =
	"profile/types/DONE_CLEARING_PROOF_OF_ADDRESS_PHOTO";
export const FAIL_CLEARING_PROOF_OF_ADDRESS_PHOTO =
	"profile/types/FAIL_CLEARING_PROOF_OF_ADDRESS_PHOTO";
export const KYC_NEXT_STEPS =
	"profile/types/KYC_NEXT_STEPS";
	
export const GET_KYC_1 = "login/types/GET_KYC_1";
export const GET_KYC_2 = "login/types/GET_KYC_2";
