/* eslint-disable max-len */
import { StyleSheet} from "react-native";
import {getStatusBarHeight} from "__src/resources/customize/StatusBarHeight";
import Resource from "__src/resources";
const {Color} = Resource;

export default StyleSheet.create({
	container: {flexShrink: 1, width: "100%", height: "100%", backgroundColor: Color.StatusBar},
	bg: {position: "absolute", flex: 1, backgroundColor: Color.white, marginTop: getStatusBarHeight(true)},
	account: {backgroundColor: "blue", marginTop: getStatusBarHeight(true)},
	body: {flex: 1, backgroundColor: Color.bg},
	wallet: {position: "absolute", zIndex: 1},
	services: {width: "100%", backgroundColor: "transparent"},

	
	imgsuccess: {width: 125, height: 125, alignSelf: "center", marginVertical: 10},
	img35: {width: 35, height: 35},
	txtsuccess: {textAlign: "center", fontFamily: "Roboto-Light", color: Color.green, fontSize: 14, marginTop: 15},
	dlWrapper: {flexDirection: "column", justifyContent: "center", alignItems: "center", marginBottom: 30},
	labelStyle2: {color: Color.black, fontWeight: "bold"},
	txtDownload: {color: Color.LightBlue, fontFamily: "Roboto-Light", fontSize: 13},

	// EcashtoEcash.js
	txtError: {color: Color.red, fontSize: 13, fontWeight: "normal", fontFamily: "Roboto-Light", marginTop: 4},
	flatlist: {paddingHorizontal: 20},
	loadView: {width: 10, height: 10},
	qrImage: {width: 22, height: 22, padding: 10},
	renderBaseWrapper: {flexDirection: "row", width: "100%",  alignItems: "center",  borderBottomColor: Color.Standard, borderBottomWidth: 0.6, paddingVertical: 3},
	txtInput: {flex: 1, fontFamily: "Roboto-Light", fontSize: 14},
	renderBaseImg: {width: 20, height: 20},
	renderRowWrapper: {paddingHorizontal: 10, flexDirection: "row", height: 40, alignItems: "center", justifyContent: "space-between", backgroundColor: "white"},
	renderRowText: {margin: 4, fontSize: 12, color: Color.Standard2, fontFamily: "Roboto-Light", textAlignVertical: "center"},
	viewDivider: {height: 0.5, backgroundColor: Color.Standard, marginTop: 8},
	modalWrapper: {flexShrink: 1, justifyContent: "center", width: "100%",
		height: "100%", paddingHorizontal: 25, paddingVertical: "10%", backgroundColor: "rgba(0, 0, 0, 0.5)"},
	modalWrapper2: {backgroundColor: "#fff", padding: 20},
	title: {color: Color.Standard2, fontFamily: "Roboto-Light", fontSize: 15},
	subtitle: {color: Color.Standard, fontFamily: "Roboto-Light", fontSize: 15},
	subtitle2: {color: Color.Standard, fontFamily: "Roboto-Light", fontSize: 14},
	txtInstruction: {color: Color.Standard2, fontFamily: "Roboto-Light", fontSize: 14, marginVertical: 10},

	amount: {color: Color.black, fontWeight: "bold"},
	value: {color: Color.colorPrimary, fontWeight: "bold"},
	valueStatus: {color: Color.red, fontFamily: "Roboto-Light" },
	valuePayment: {color: Color.Standard2, fontFamily: "Roboto-Light", textAlign: "left" },
	valuePayment2: {color: Color.Standard2, fontFamily: "Roboto-Light", fontWeight: "bold", textAlign: "left" },
	modalWrapper3: {width: "100%", flexDirection: "row", justifyContent: "flex-end", marginTop: 40},
	modalBtn: {flex: 1, borderColor: Color.colorPrimary, borderWidth: 0.5,
		backgroundColor: Color.white, marginRight: 5},
	width120: {flex: 1, marginLeft: 5},
	
	
	txtLabel: {color: Color.Standard, fontSize: 14, fontFamily: "Roboto-Light"},
	viewTarget: {flexDirection: "row", width: "100%", height: 40, alignItems: "center",  borderBottomColor: "#404040", borderBottomWidth: 0.6},
	viewReason: {flexDirection: "row", width: "100%", height: 60,  borderBottomColor: "#404040", borderBottomWidth: 0.6},
	txtConvertAmt: {textAlign: "right", fontFamily: "Roboto", fontSize: 15, color: Color.Standard2, marginTop: 15},
	btnProceed: {marginHorizontal: 20, borderBottomWidth: 6, marginBottom: 20},
	targetDropdown: { height: 120},
	txtCode: {fontSize: 10, color: Color.Standard, marginTop: 5},
	txtNote: {color: Color.red, fontSize: 13, fontWeight: "normal", fontFamily: "Roboto-Light", marginTop: 4},
	walletWrapper: {flexDirection: "row", justifyContent: "space-between", backgroundColor: Color.gray06,
		padding: 20, alignItems: "center"},
	flexColumn: {flexDirection: "column"},
	walletTxtSource: {fontFamily: "Roboto-Light", fontSize: 17, color: Color.Standard2},
	walletTxtSourceValue: {fontFamily: "Roboto", fontSize: 17, color: Color.colorPrimaryDark},
	walletTxtSourceWallet: {fontFamily: "Roboto-Light", fontSize: 17, color: Color.Standard2, marginTop: 10},
	walletTxtSourceWalletValue: {fontFamily: "Roboto", fontSize: 17, color: Color.colorPrimaryDark},
	walletTxtSourceWalletValue2: {fontSize: 13, color: Color.Standard},
	walletTxtAccountType: {fontFamily: "Roboto-Light", fontSize: 14, color: Color.Standard},

	// Conversion
	conRenderBase: {flexShrink: 1, flexDirection: "row", height: 40, alignItems: "center" },
	conRBImg: {width: 22, height: 22, borderRadius: 11, backgroundColor: Color.gray06},
	conRBTxt1: {marginLeft: 5, fontFamily: "Roboto-Light", fontSize: 14, color: Color.Standard2},
	conRBTxt2: {marginLeft: 5, fontFamily: "Roboto-Light", fontSize: 14, color: Color.white},
	conRenderRow: {paddingLeft: 7, flexDirection: "row", height: 40, alignItems: "center", justifyContent: "flex-start", backgroundColor: "white"},
	conRRImg: {width: 22, height: 22},
	conRRTxt: {margin: 4, fontSize: 13, color: Color.Standard, fontFamily: "Roboto", textAlignVertical: "center"},
	conCard: {borderRadius: 5,	marginLeft: 0, marginRight: 0},
	conView1: {backgroundColor: Color.Header, padding: 20, paddingTop: 30,
		borderTopRightRadius: 5, borderTopLeftRadius: 5},
	conView2: {flex: 1, backgroundColor: Color.white, padding: 20, paddingTop: 20, borderRadius: 5},
	conView3: {flex: 1, alignItems: "flex-end"},
	conView4: {marginHorizontal: 30, alignItems: "center", marginTop: 15},
	conView5: { width: 150, height: 0.7, backgroundColor: Color.Standard, marginVertical: 5},
	conView6: {flexGrow: 1, alignItems: "center", justifyContent: "center"},
	flexRow: {flexDirection: "row"},
	flexCol: {flexDirection: "column"},
	conImgSwitch: {width: 30, height: 25},
	conBtnSwitch: {position: "absolute", left: 18, zIndex: 10, elevation: 3},
	contxt1: {color: Color.Standard2, fontFamily: "Roboto-Light", fontSize: 16},
	contxt2: {color: Color.white, fontFamily: "Roboto-Light", fontSize: 16},
	contxt3: {alignSelf: "flex-end", color: Color.white, fontFamily: "Roboto-Light", fontSize: 14 },
	contxt4: {flex: 1, color: Color.LightBlue, fontFamily: "Roboto-Light", fontSize: 22, fontWeight: "bold", textAlign: "right", marginTop: 25},
	contxt5: {textAlign: "right", color: Color.Standard2, fontFamily: "Roboto-Light", fontSize: 14 },
	contxt6: {color: Color.Standard2, fontFamily: "Roboto-Light", fontSize: 14},
	contxt8: {textAlign: "center", marginTop: 10, color: Color.Standard2, fontSize: 12, fontFamily: "Roboto-Light", paddingHorizontal: 10},
	contxt9: {textAlign: "center", backgroundColor: Color.lightred, padding: 10, color: Color.red, fontSize: 12, fontFamily: "Roboto-Light"},
	contxtInput: {flex: 1, color: Color.colorPrimary, fontFamily: "Roboto-Light", fontSize: 22, fontWeight: "bold", textAlign: "right", marginTop: 15},
	condropdown: {height: 150, width: 70},
	conBtnConvert: {borderBottomWidth: 6, marginBottom: 20},
	txtDiscount: {fontFamily: "Roboto", fontSize: 13, color: Color.Standard2},

	mainContainer: {flex: 1, paddingHorizontal: 20,  backgroundColor: Color.white},
	flex1: {flex: 1},
	flexShrink1: {flexShrink: 1},
	flex1marT15: {flex: 1, marginTop: 15},
	flex1marT20: {flex: 1, marginTop: 20},
	flex1marV20: {flex: 1, marginVertical: 20},
	flex1allCenter: {flexShrink: 1, alignItems: "center", justifyContent: "center"},
	flex1padH20: {flex: 1, paddingHorizontal: 20},
	flex1marT30padH20: {flex: 1, paddingHorizontal: 20, marginTop: 20},
	marT10: {marginTop: 10},
	marT15: {marginTop: 15},
	marT20: {marginTop: 20},
	marT30: {marginTop: 30},
	marB10: {marginBottom: 10},
	marB20: {marginBottom: 20},
	txt: {marginLeft: 100},
	padmar0: {paddingBottom: 0, paddingTop: 0, marginTop: 0, marginBottom: 0},
	input: {flex: 1, fontFamily: "Roboto-Light", fontSize: 15, marginLeft: 5, paddingVertical: 0},
	input2: {fontFamily: "Roboto-Light", fontSize: 15, marginLeft: 3},
	input3: {fontFamily: "Roboto-Light", fontSize: 12, color: Color.Standard},
	input4: {flex: 1, fontFamily: "Roboto-Light", fontSize: 14, paddingVertical: 0},
	txt1: {fontFamily: "Roboto-Light", textAlign: "center", color: Color.LightBlue, fontWeight: "bold", fontSize: 22},
	txt2: {fontFamily: "Roboto", color: Color.Standard2, fontSize: 21},
	txt3: {textAlign: "center", fontFamily: "Roboto-Light", color: Color.Standard2, fontSize: 13},
	txt3_1: {textAlign: "center", fontFamily: "Roboto-Light", color: Color.Standard2, fontSize: 20},
	txt4: {textAlign: "center", fontFamily: "Roboto-Light", color: Color.Standard2, fontSize: 14},
	txt5: {fontFamily: "Roboto", fontSize: 18, color: Color.Standard, marginLeft: 10},
	txt6: {fontFamily: "Roboto", fontSize: 13, color: Color.Standard2},
	txt7: {flexShrink: 1, paddingVertical: 0, fontFamily: "Roboto-Light", fontSize: 12, color: Color.Standard2},
	txt8: {flexShrink: 1, paddingVertical: 0, fontFamily: "Roboto", color: Color.LightBlue, fontSize: 21},
	cardView1: {padding: 13, alignItems: "center", justifyContent: "center", minHeight: 80,
		marginLeft: 0, marginRight: 0, marginTop: 10, marginBottom: 0, borderRadius: 5},
	cardView2: {padding: 10, flexDirection: "row", alignItems: "center", justifyContent: "center",
		marginLeft: 0, marginRight: 0, marginTop: 0, marginBottom: 0},
	cardView3: {position: "absolute", bottom: -40, zIndex: 2, marginLeft: 0, marginRight: 0},
	cardView4: {position: "absolute", bottom: -40, zIndex: 2, marginLeft: 0, marginRight: 0},
	iconContainerStyle: {position: "absolute", left: 5, top: 8},
	img1: {width: 125, height: 125, alignSelf: "center", marginVertical: 20},
	img2: {width: 65, height: 50},
	img3: {width: 35, height: 35, marginVertical: 7},

	renderSuccessWrapper: {flex: 1, padding: 30, flexDirection: "column", justifyContent: "space-between"},
	renderSuccessWrapper2: {justifyContent: "center", alignItems: "center", marginBottom: 20},
	txtok: {color: Color.colorPrimary, fontSize: 18, alignSelf: "center", paddingHorizontal: 30, paddingVertical: 10},
	zIndex1: {zIndex: 1},
 
	// LOCALSCREEN
	btnCreate: {marginHorizontal: 20, borderBottomWidth: 6, marginBottom: 5},
	btnCancel: {backgroundColor: Color.transparent, color: Color.colorPrimaryDark,
		 marginHorizontal: 20, borderBottomWidth: 0, marginBottom: 5},
	paddingTop5: {paddingTop: 5},

	// INPUT
	inpuView1: {justifyContent: "center", backgroundColor: Color.lightred, padding: 7, marginTop: 10, borderRadius: 3, flexDirection: "row"},
	txtAlign: {textAlign: "right"},
	inputCard1: {paddingVertical: 30, paddingHorizontal: 15,
		marginLeft: 0, marginRight: 0, marginTop: 10},
	alignSelf: {alignSelf: "flex-end"},
	planView1: {width: 65, borderRadius: 65 / 2, height: 65, borderColor: Color.LightBlue, borderWidth: 1, flexDirection: "column",
		alignItems: "center", justifyContent: "center"},
	width70: {width: "75%"},
	justSpace: {flexDirection: "column", justifyContent: "space-between"},
	dropdownstyle: {width: 300, height: 250, borderColor: "#D9D8D8",
		marginTop: 3, borderWidth: 1, borderRadius: 5},
	dropdownRow: {flexDirection: "row", height: 40, alignItems: "center", backgroundColor: "white"},
	dropdownRowText: {marginLeft: 5, fontSize: 13, fontFamily: "Roboto-Light", color: Color.Standard2},
	dropdownRowText2: {fontWeight: "bold"},
	renderSearch: {height: 40, borderBottomColor: Color.Standard,
		 borderBottomWidth: 0.5, marginTop: 5},
	views_bi3: { flexShrink: 1, flexDirection: "row", justifyContent: "center", alignItems: "center", height: 40},
	labelStyle: {color: Color.Standard, fontSize: 14, fontFamily: "Roboto-Light"},
	textfields: {fontSize: 14, fontFamily: "Roboto-Light"},

	input6: {flex: 1, borderRadius: 30, fontFamily: "Roboto", fontSize: 16, paddingVertical: 0, backgroundColor: Color.transparent},
	view1: {flexDirection: "row", marginTop: 50, alignItems: "center", justifyContent: "space-between"},
	view2: {flexDirection: "row", flexShrink: 1, height: 40, alignItems: "center",
		justifyContent: "center", borderWidth: 1, borderColor: Color.text1, borderRadius: 25, paddingHorizontal: 10},
	view3: {flexDirection: "row", flex: 1, height: 40, alignItems: "center", justifyContent: "center",
		borderWidth: 1, borderColor: Color.text1, borderRadius: 25, paddingHorizontal: 15, marginLeft: 7},
	view4: {flexDirection: "row", flexShrink: 1, height: 40, alignItems: "center",
		justifyContent: "center", paddingHorizontal: 10},
	imageCurrency: {width: 26, height: 26},
	imageCurrency1: {width: 14, height: 14},
	txtNumber: {flexGrow: 2, fontFamily: "Roboto", fontSize: 16, color: Color.Header, marginLeft: 7},
	txtNumber1: {flexGrow: 2, fontFamily: "Roboto", fontSize: 12, color: Color.Header, marginLeft: 7},
	loadBanner: {height: 200, width: "105%"},

	// PAYMENT
	payView1: {justifyContent: "center", backgroundColor: "#bde5f8", padding: 7, marginTop: 10, flexDirection: "row"},
	payIcon: {position: "absolute", left: 5, top: 6},
	payCard1: {padding: 20, alignItems: "center", justifyContent: "center",
		marginLeft: 0, marginRight: 0, borderRadius: 5},
	payCard2: {padding: 20, marginLeft: 0, marginRight: 0, borderRadius: 5},
	payView2: {paddingBottom: 5},
	viewImage: {marginTop: 20, alignItems: "center", justifyContent: "center"},


});
