import {StyleSheet} from "react-native";
// import {getStatusBarHeight} from "__src/resources/customize/StatusBarHeight";
import Color from "__src/resources/styles/color";

export default StyleSheet.create({
	container: {flex: 1, width: "100%", height: "100%", backgroundColor: "#F8F9FB"},
	body: {flex: 1},
	imagebackground: {width: "100%", height: "100%", position: "absolute"},
	
	// LoginForm
	flex1: {flex: 1},
	flexRow: {flexDirection: "row"},
	txtLanguage: {marginLeft: 20, fontFamily: "Roboto", fontWeight: "bold", fontStyle: "normal", fontSize: 12, marginRight: -3},
	marginTop10: {marginTop: 10},
	height90: {height: "94%"},
	top: { height: "30%", paddingTop: 10, alignItems: "center"},
	middle: { height: "67%", paddingHorizontal: 20},
	bottom: { height: "6%", backgroundColor: Color.StatusBar, justifyContent: "center", alignItems: "center" },
	imageLogo: {width: "28%", height: "70%"},
	txtError: { color: "red", fontFamily: "Roboto-Light", fontSize: 15, textAlign: "center", marginBottom: 5},
	txtHelpContainer: {fontSize: 12, fontWeight: "bold", fontFamily: "Roboto", marginVertical: 10, color: Color.white, textAlign: "center" },
	txtHelp: {fontSize: 12, fontWeight: "bold", color: Color.colorPrimary, textDecorationLine: "underline", fontFamily: "Roboto"},
	txtGetHelpContainer: {fontSize: 13, marginTop: 10, marginBottom: 7, color: "#FFC914", fontFamily: "Roboto", textAlign: "center", textDecorationLine: "underline", fontWeight: "bold"},
	txtGetHelpContainer2: {fontSize: 14, fontWeight: "bold", marginVertical: 10, color: Color.Standard2, fontFamily: "Roboto-Light", textAlign: "center" },
	txtfb: {color: Color.blue, fontSize: 15, fontFamily: "Roboto-Light"},
	btnfb: {height: 45, marginTop: 15, alignItems: "center",
		backgroundColor: "transparent", flexDirection: "row", justifyContent: "center" },
	loadview: {width: 10, height: 10},
	btnlogin: {width: "94%", height: "10%", borderBottomWidth: 0, marginTop: 10, borderRadius: 100, backgroundColor: "#FFC914", 
		elevation: 5},
	// viewLogin: {flexShrink: 1, backgroundColor: Color.colorPrimary},
	viewFBWrapper: {flexDirection: "row", alignItems: "center", justifyContent: "center", marginVertical: 10},
	viewLine: {flex: 1, height: 0.7, backgroundColor: Color.white},
	txtSocial: {fontSize: 13, marginHorizontal: 10, fontFamily: "Roboto-Light", color: Color.white },
	imgFb: {width: 40, height: 40, marginRight: 8},
	shadow: {borderBottomWidth: 5, borderBottomLeftRadius: 15, borderBottomRightRadius: 5, borderColor: "rgba(0, 0, 0, 0.10))"},
	inputFieldStyle: {justifyContent: "center", width: "95%", height: "10%", borderRadius: 8, backgroundColor: "#F6F6F6", borderWidth: 1, borderColor: "#E8E8E8", borderStyle: "solid"},
	passwordFieldStyle: {width: "95%", borderRadius: 8, backgroundColor: "#F6F6F6", borderWidth: 1, borderColor: "#E8E8E8", borderStyle: "solid", flexDirection: "row", justifyContent: "space-between", marginTop: 10},
	termStyle: {color: "#FFC914", textDecorationLine: "underline"},
	textInputStyle: {paddingVertical: 0, marginTop: 0, marginLeft: 10, fontSize: 14, fontFamily: "Roboto", color: "#000000", fontWeight: "bold"},
	showPass: {height: "100%", width: "70%"},
	hidePass: {marginTop: 4, height: "100%", width: "70%"},
	otherLoginView: {flexDirection: "row", justifyContent: "center", alignItems: "center", height: "100%", width: "85%", borderRadius: 15, elevation: 4},
	otherLoginLogo: {height: 18, width: 10, marginRight: 10},
	otherLoginStyle: {fontSize: 13, fontFamily: "Roboto", color: "#FFFFFF"},
	btnLabelStyle: {fontSize: 14, fontFamily: "Roboto", fontWeight: "bold"},
	txtTermsContainer: {width: "90%", textAlign: "center", fontFamily: "Roboto", fontWeight: "bold", fontSize: 12},

	// OTPForm
	viewContainer: {flex: 1, backgroundColor: "#F8F9FB", alignItems: "center"},
	imageContainer2: {alignItems: "center"},
	viewflex2: {flex: 2, paddingHorizontal: 20},
	txtOtp: {textAlign: "center", fontFamily: "Roboto", fontWeight: "bold", color: Color.Standard2, fontSize: 17, marginBottom: 15},
	txtOtpnote: {fontFamily: "Roboto-Light",  fontSize: 13, color: Color.Standard2, marginBottom: 5},
	containerStyle: {marginLeft: 0, padding: 0, marginTop: 10, backgroundColor: "transparent", borderColor: "transparent"},
	textStyle: {fontFamily: "Roboto-Light", fontWeight: null, fontSize: 14, color: Color.Standard2},
	otpBottom: {marginTop: 15, marginBottom: 5},
	btnback: {width: 120, borderColor: Color.colorPrimaryDark,
		backgroundColor: Color.white, marginRight: 10},
	width120: {width: 120},
	backArrow: {elevation: 5, marginLeft: 20, marginTop: 20, alignSelf: "flex-start", padding: 10, height: 36, width: 36, backgroundColor: "#FFC914", borderRadius: 38, borderBottomWidth: 0},
	otpHeader: {marginTop: -15, marginBottom: 10, alignSelf: "center", fontWeight: "700", fontSize: 20, fontFamily: "Roboto"},
	mobileField: {width: 200, height: 45, paddingLeft: 15, borderRadius: 36, borderWidth: 1, borderColor: "#FFC914", borderStyle: "solid"},
	prefixField: {padding: 10, width: 100, height: 45, borderRadius: 36, borderWidth: 1, borderColor: "#FFC914", borderStyle: "solid"},
	otpBody: {elevation: 5, backgroundColor: "#FFFFFF", marginTop: 20, marginBottom: 100, width: 350, borderRadius: 36},
	
	// FBRegistration
	modalContainer: {flexShrink: 1,  width: "100%", height: "100%",
		paddingHorizontal: 20, paddingVertical: 30, backgroundColor: "rgba(0, 0, 0, 0.5)"},
	modalView1: {backgroundColor: "#fff", justifyContent: "center", borderRadius: 3, padding: 10},
	margin15: {marginTop: 15},
	labelStyle: {color: Color.Standard, fontSize: 14, fontFamily: "Roboto-Light"},
	views_bi3: {flexDirection: "row", alignItems: "center", width: "100%", height: 40,  borderBottomColor: Color.Standard, borderBottomWidth: 0.6},
	view1: {flex: 1, flexDirection: "column", marginTop: 15},
	view2: {paddingHorizontal: 10, paddingVertical: 2, borderRadius: 5,
		backgroundColor: Color.Standard, marginRight: 10},
	txt1: {fontSize: 14, fontFamily: "Roboto", color: Color.white},
	errStyle: {color: Color.red, fontSize: 13, fontFamily: "Roboto-Light", marginTop: 4},
	dropdownstyle: {width: 200, height: 250, borderColor: "#D9D8D8",
		marginTop: 3, borderWidth: 1, borderRadius: 5},
	dropdownRow: {flexDirection: "row", height: 40, alignItems: "center", backgroundColor: "white"},
	dropdownRowText: {marginLeft: 5, fontSize: 13, fontFamily: "Roboto-Light", color: Color.DarkBG},
	dropdownRowText2: {fontWeight: "bold"},
	textfields: { flex: 1,  fontSize: 14, fontFamily: "Roboto-Light"},
	icon: {padding: 5, borderRadius: 5},
	txtFb: {fontSize: 18, fontFamily: "Roboto", color: Color.Standard2, paddingVertical: 5},
	inputStyles: {fontSize: 18, color: Color.Standard2},
	borderWidth0: {borderBottomWidth: 0},

	// renderError
	inpuView1: {justifyContent: "center", backgroundColor: Color.lightred, padding: 7, marginTop: 10, flexDirection: "row"},
	iconContainerStyle: {position: "absolute", left: 5, top: 8},
	txt3: {textAlign: "center", fontFamily: "Roboto-Light", color: Color.Standard2, fontSize: 13},

	// Welcome
	welcomeBG: {flex: 1, justifyContent: "center", backgroundColor: "rgba(0, 0, 0, 0.5)"},
	welcomeBody: {margin: -25, borderRadius: 36, width: 350, alignSelf: "center", backgroundColor: "#FFFFFF"},
	welcomeMsg: {color: "#FFC914", fontSize: 21, fontWeight: "bold", fontFamily: "Roboto", textAlign: "center"},
	welcomeCloseBtn: {alignSelf: "flex-end", backgroundColor: "#FB4646", borderWidth: 0, width: 35, height: 35, borderRadius: 30},
	welcomeBtnStyle: {elevation: 5, alignSelf: "center", marginTop: 15, borderRadius: 100, backgroundColor: "#FFC914", height: 45, width: 259},
	welcomeBtnLabel: {color: "white", fontSize: 14, fontWeight: "bold"},
	welcomeIMG: {alignSelf: "center", marginTop: 45, height: 220, width: 220},

	// Privacy Policy
	fontTitleStyle: {paddingVertical: 20, fontFamily: "Roboto", fontWeight: "bold", fontSize: 18},
	fontStyle: {fontSize: 15, fontFamily: "Roboto"},
	privacyBG: {flex: 1, paddingVertical: 30, justifyContent:"center", alignItems: "center", backgroundColor: "rgba(0, 0, 0, 0.5)"},
	privacyBTN: {elevation: 4, width: 280, height: 35, backgroundColor: "#FFC914", borderBottomWidth: 0, borderRadius: 90},
	privacyLabel: {fontWeight: "bold", fontSize: 14},

	// T&C
	TACBody: {flexShrink: 1, marginHorizontal: 15, marginTop: -25, marginBottom: 10, backgroundColor: "white", borderRadius: 36},
	italic1: {fontSize: 15, fontFamily: "Roboto", fontStyle: "italic", marginTop: 10, marginHorizontal: 7},
	italic2: {fontSize: 15, fontFamily: "Roboto", fontStyle: "italic", marginTop: 10, marginHorizontal: 10},
	textStyle1: {fontSize: 15, fontFamily: "Roboto", marginTop: 10, marginHorizontal: 10},
	textStyle2: {fontSize: 15, fontFamily: "Roboto", marginTop: 10, marginHorizontal: 7},
	numberStyle1: {fontSize: 15, fontFamily: "Roboto", marginTop: 10},
	numberStyle2: {fontSize: 15, fontFamily: "Roboto", marginLeft: -2, marginTop: 10},
	marL15flexRow: {marginLeft: 15, flexDirection: "row"},

	// Change Password
	modalContainerCP: {flexGrow: 1, justifyContent: "center", paddingHorizontal: 15, backgroundColor: "rgba(0, 0, 0, 0.5)"}, 
	modalViewCP: {paddingVertical: 20, backgroundColor: "#FFFFFF", borderRadius: 36},
	topImage: {alignSelf: "center", height: 85, width: 85},
	clsBtnView: {marginRight: 10, zIndex: 1},
})
;
